### ISSUE TITLE
sass-loader 的 peerDependencies 

### ISSUE THREAD

**Issue by nighca** [vikingmute/deskmark#1]
sass-loader 的 peerDependencies 里有 node-sass@^3.4.2。
npm3 以后不会自动安装 peerDependencies 了，这个是不是给加到 package.json 来。没问题的话我就来发我的第一个 pr。

**Comment by vikingmute** [comment]
@nighca 好啊 我的npm版本是旧的 所以没有遇到这个问题 也帮忙review一下简单版的代码  现在目前简单版本和redux版本的代码分别放在两个文件夹中 我们要不要分别建branch？或者是什么好方法？

**Comment by nighca** [comment]
@vikingmute 这俩不是分支间的关系，我觉得就放两个文件夹吧。
不过现在好像一个是 app 一个是 src？这个命名有点奇怪。

**Comment by vikingmute** [comment]
@nighca  想名字想了半天 你有啥好名字直接说出来吧 我这个就是临时起的 很不合理

**Comment by nighca** [comment]
@vikingmute 特点上区分开就好了吧，像
app vs app-with-redux
deskmark vs deskmark-with-redux
这种？

**Comment by nighca** [comment]
参考这边，也是差不多的组织方式：
https://github.com/reactjs/redux/tree/master/examples
最好是 package.json、 webpack.config.js 这些文件也都放在各自的目录里组织吧

**Comment by vikingmute** [comment]
@nighca 好的  明天有空搞一下 有空review一下代码～ 简单版本的

**Comment by nighca** [comment]
@vikingmute :ok_hand:
