### ISSUE TITLE
React v15

### ISSUE THREAD

**Issue by nighca** [vikingmute/deskmark#15]
考虑升级 React 到版本 15，改动不大，应该基本可以无缝升级

**Comment by vikingmute** [comment]
http://stackoverflow.com/questions/35890730/react-15-not-compatible-with-react-redux 各种peer dependencies 又不想升级npm3  😢

**Comment by nighca** [comment]
:smile: 作者在下边回出新的基于 react@15 的版本了，我下次试试看，不麻烦就升级下

**Comment by vikingmute** [comment]
还有一个react－test-suite要升级。。我考虑要不要npm update -g,你npm是啥版本

**Comment by nighca** [comment]
3.x 的

**Comment by vikingmute** [comment]
https://github.com/vikingmute/deskmark/commit/1fe6ba8cafab9eb2eb613b0525d9739dae67bfc7
好了 升级好了 需要3.X 版本

**Comment by nighca** [comment]
:+1:
